[lib]
proc-macro = true

[package]
name = "chell-macros"
version = "8.3.0"
edition = "2024"

[features]
ground = []

[dependencies]
heck = "0.5.0"
syn = { version = "3.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
